@version: 3.38
@include "scl.conf"

options {
  time-reap(30);
  keep-hostname(yes);
  chain-hostnames(no);
  use-dns(no);
  create-dirs(yes);
};

source s_fortigate_udp {
  udp(ip("0.0.0.0") port(514));
};

template t_forti_line {
  template("${ISODATE} host=${HOST} ${MSG}\n");
};

destination d_fortigate_files {
  file("/var/log/fortigate/${HOST}.log"
       template(t_forti_line)
       flush-lines(1));
};

log {
  source(s_fortigate_udp);
  destination(d_fortigate_files);
};
